### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbphp6#12]
For now the build version (in mdbBase.php) is set to 1.1.5
It seems right to me after all the changes to imdbphp to start at version 1.1.5?

I'm thinking of getting ready for a release build but i'm doing this only if you all approve it.

So my question to you all is to test every method, report any issues through a new issue (if there are any left)
If everybody seems happy about it i will make a release indicating a stable version to use.

Then comes the hard part.. writing documentation, i'm planning to make a list of all methods with their in and outputs described but that is a future plan.

Edit:
Release will have to wait as there are still some things to sort out.

**Comment by GeorgeFive** [comment]
I FINALLY had some time to get caught up on all of the recent changes.... most of this time was spent updating my own code to completely move away from boothman's version.  I've been doing some serious testing before I go live with this on my actual site, and honestly, I haven't found any problems.  I do not use every available function (and haven't tested the budget stuff yet), but the ones I do use work great.  Also, I've removed my PHP 5.6 workaround and everything is working in this version... awesome!

**Comment by duck7000** [comment]
Release versions are now done, V1.1.4 just released to fix a bug with recommendations

So this one can be closed i guess
