### ISSUE TITLE
photo_localurl / savephoto

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbphp6#16]
Anyone have needs for this?

I don't use it but if others do i might consider to re-add it again.

@jcvignoli did mentioned this as missing, not sure if this is still a issue.

Saving images is not that hard to implant in the program where you use this library. I save those images directly from the url with curl

**Comment by jcvignoli** [comment]
Always looking for such function 😎

**Comment by duck7000** [comment]
Okay, i will re add it

**Comment by duck7000** [comment]
@jcvignoli 
Did you test this jet?

For now i have added untested to those methods in the wiki page

**Comment by jcvignoli** [comment]
@duck7000 I haven't yet, I'd require time to test it and right now I'm a bit busy. Will let you know asap!

**Comment by duck7000** [comment]
Oh okay i was just curious :)

**Comment by duck7000** [comment]
I just spotted a bug in photo_localurl, fixed that.

**Comment by jcvignoli** [comment]
Hi @duck7000,
Unless I'm mistake, you're just took out debug_scalar() and other logging methods, right?
I guess you have no need for debugging. For me it is mandatory, the project I've been working on implements a lot of debugging facilities to help me in the bug hunting.
I'm afraid I can't either implement or test photo related functions.

**Comment by duck7000** [comment]
Yes i did strip those out.
This library either works or not. Not that difficult i imagined
For my needs i only need the movie/ tv show data to save in my database (i have a catalog program) so no need for logging or debugging.
I never imagined that other users use this library in different ways, so everybody has different needs

If no logging or debugging is a deal breaker for you i'm sorry but then this library is not for you i guess. My version is not a fork, it is a different version (although a large part is practical the same) Next to this i already added a few methods/changed a few methods on request of other users. My initial goal was a stripped down/clean version for my needs only but that is already growing fast. I don't want to end up with a complete fork.

There is a reason i did make my own version as i was getting tired of the lack of interest from tboothman, not even look at PR's, and if he did i get an answer like: i don't understand what you fixed as my test show it still works..

You will have to wait for tboothman (if he is ever going to..) (or others but even PR's are not even looked at..) to fix all methods or fix all methods yourself as you are depending on logging and debugging.
Or saving those images can be done inside your application instead using methods from this library? Personally i don't think those methods belong in this library, but i can be wrong off course.

I'll give you, and others, permission to use my work to fix tboothmans version if you want (my work is gpl too)

If you are not using savephoto or photo_localurl i will remove them as nobody else (including me) is using this.
If you do know a way for you to using it let me know but i'm not implanting logging and or debugging, i hope you understand that.

**Comment by jcvignoli** [comment]
No problem at all, @duck7000! While I don't use your libraries as they are, I copy paste the various fixes you implemented into a fork of imdbphp. This allows me to maintain my own project quite easily.
Thanks again for your wok!

**Comment by duck7000** [comment]
Well that is certainly also a solution:)

I expect not that many changes on graphql imdb api as i look at the change log at their site so it shouldn't be a problem to maintain your own fork, just like i did
Although it is a shame that a lot of people has to maintain their own forks while tboothman does not maintain his i guess.
But on the other hand it gives all those users the opportunity to make their fork for their needs.

I will remove savephoto and photo_localurl, agree?

**Comment by jcvignoli** [comment]
absolutely!

**Comment by duck7000** [comment]
okay i will close this issue as solved
