### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/imdbphp6#17]
First up... I have completely switched over to your version as of tonight, and everything is working as expected.  Kudos!!

Now, a question.  My code currently uses the caching functionality from boothman's version.  I don't particularly NEED it, but it does come in handy when testing / debugging / etc.  I've noticed that your version stripped the caching stuff out.  Do you have any plans to bring this over?  It's not a huge issue if not, but I just wanted to see what your plans were before I stripped it out of my own code.  Currently, my code just skips over it (no cache, no problem, fetch live, cache is never built), but it does check for it every time.  If there are no plans for it, I'll just remove the check on my end.

**Comment by duck7000** [comment]
Thanks for the kudos :)

Yes i stripped cache as well as other debug stuff i didn't need. I use imdbhp6 to add movie/tv series info in my program so i want "fresh" non cached info. Caching has no point in my program as i never use it.
Another point is that if something isn't working it is quite simple to debug, put a var_dump() in the method that isn't working to check where it don't work. Now with GraphQL that chance is slim though, if i look at the release notes from imdb about graphql there isn't much changes. What can happen is that stuff get deprecated and replaced.

So to come back to your question, no i'm not bringing this back. So you can safely remove it.

Maybe a milestone file is something i need to consider? That way i can show what i may have planned for future versions.

For now my priority lies in a stable release version so we have a stable base to work of/with

**Comment by duck7000** [comment]
@GeorgeFive 
Did you test/are you using a methods in title, if so everything is working like it should?
If not can you give a list of tested methods so i know those are working?

Do you use the person class as well?
Did you test/are you using a methods in person, if so everything is working like it should?
If not can you give a list of tested methods so i know those are working?

**Comment by GeorgeFive** [comment]
Yeah, I'm not too concerned with caching, I just thought of it last night when I was trying to change some stuff in my own code... my changes didn't work, edit code, refresh, wait 10-15 seconds for the episodes list to reload, still didn't work, edit, refresh, wait... I thought, damn, caching would have helped here, haha.

Milestones might be cool.  There are some things that I think would be cool to have, but I was trying to limit my requests to only stuff I needed to make the transition until we hit a stable point (and I didn't want to overload you).

In title, I'm using:

countries
credits_cast
credits_composer
credits_director
credits_producer
credits_writer
main_rating
votes
episode
compcred_prod
compcred_dist

I still haven't brought budget over, and I'll be bringing filming locations over as well.... whenever I get time....

In person, I'm using:

main_photo
fullname
birthday
deathday
birth_name
nick_name

Also, I use titlesearch, but not personsearch.

Everything I'm using in here seems to work perfectly, haven't had any issues.

**Comment by duck7000** [comment]
Thanks for your feedback!

The things that you might want to add will make it in the milestone file/list for sure but first a stable version because we need something stable that is working right.
After that i will try to make your, or others, requests working.

I'm going to make a list with all title and person methods, with your feedback i can mark those as tested and working
