### ISSUE TITLE
movietype helper text

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/imdbphp6#18]
Not a bug in your code, but you may want to change the help text a bit for the movietype function.  This took me a few to figure out, so it may help others.

@return string movietype (TV Series, Movie, TV Episode, TV Special, TV Movie, TV Mini-Series, Video Game, TV Short, Video)

"TV Mini-Series" is supposed to be "TV Mini Series" (no dash).
https://www.imdb.com/title/tt7366338/

**Comment by duck7000** [comment]
Ah i see, a left over from tboothman's version i guess.
I will change that, consider it done.

**Comment by duck7000** [comment]
So the importance of a good description what every method is doing and outputting is crucial, not only in doc block but also in readme or wiki.
I'll add it to the milestone file i made
