### ISSUE TITLE
Episodes default  based season

### ISSUE THREAD

**Issue by Thomasdouscha** [duck7000/imdbphp6#19]
I cannot say episodes is default based on season. Your check code still does decide about season or year based. Please let it to us to decide which one. Except this, is working very well

**Comment by duck7000** [comment]
I did let that check in to prevent huge amount of episodes in 1 season.
We discussed this before

**Comment by duck7000** [comment]
but your point being that you want full control on year or season based, so only you as user will have that control?
Fine, i will remove it.

**Comment by duck7000** [comment]
It is remove now, i surely hope that episodes is now acceptable to anyone

**Comment by Thomasdouscha** [comment]
Thanks a lot. Tonight i will check it

**Comment by Thomasdouscha** [comment]
`<html><body>


message | "Call to undefined method Imdb\\Title::episodes()"
-- | --
exception | "Symfony\\Component\\Debug\\Exception\\FatalThrowableError"
file | "/mnt/diskssd/web/site_copy/app/Http/Controllers/Movie/MovieController.php"
line | 7064


</body>
</html>

And this line's code is `$arr = $imdb->episodes();	`

Unfortunately is not working!

**Comment by Thomasdouscha** [comment]
Hmmm i see not episodes() it should be episode() Again i am trying

**Comment by Thomasdouscha** [comment]
Get episodes but till 250.episodes. Code has some limit value? 
I did yearbased did not get year episodes. And did not give any errors. It does not work well enough. I have test for one piece.

Mynote: Before your revision It does get all year episodes very fast. I think it does get episodes even more than ten thousand episodes.

**Comment by Thomasdouscha** [comment]
I think there is a limit 250 for based episodes.
![image](https://github.com/duck7000/imdbphp6/assets/43930732/afea6540-9f09-4447-903f-be42237b5a67)

**Comment by Thomasdouscha** [comment]
Because of your code or imdb graphql ? I don't know

**Comment by Thomasdouscha** [comment]
If yearbased it can get episodes more then 9000 episodes vaaavv.

![image](https://github.com/duck7000/imdbphp6/assets/43930732/b35bcdd6-1d5b-4060-b058-5764e5be1459)

**Comment by duck7000** [comment]
First of all i don't understand exactly what you are saying/what is your problem?
Probably your English is not that good i guess as your text here is not making enough sense to me

No there is no limit anywhere in my code, except there is a limit in graphql so maximum episodes is 9999
If there are any other limits i don't know about it/ i can't know about it because that information is not available.
So maybe there is al limit of 250 for, i guess you mean season based? I don't know

You get 250 episodes with what? season or year based?
It can be a memory limit of php ?
It can be max execution time of php?

Maybe my method is not good enough to work with this kind of, in my opinion, crazy amount of episodes. For your information the tboothman version doesn't even get those episodes, it breaks the method.
So i'm already glad it even works

**Comment by duck7000** [comment]
i think it is safe to say that this kind of tv series is not possible based on seasons, it is simply too much i guess or imdb has a limit on it and requires a pro membership, it seems logic.

That is exactly why i left that check in, it prevents this from happening as it returns year based even if you set parameter $yearbased = 1

i surely hope that you understand?

@georgefive what do you think about this? Is this also a problem at your end?

**Comment by duck7000** [comment]
I think there are 2 options left:

I revert the latest code change.
Or change that latest code change to break the method if the check outputs year based? So an empty array is returned?

This whole situation does not lead to any improvements so we have to choose one or the other.

**Comment by Thomasdouscha** [comment]
> First of all i don't understand exactly what you are saying/what is your problem? Probably your English is not that good i guess as your text here is not making enough sense to me
> 
> No there is no limit anywhere in my code, except there is a limit in graphql so maximum episodes is 9999 If there are any other limits i don't know about it/ i can't know about it because that information is not available. So maybe there is al limit of 250 for, i guess you mean season based? I don't know
> 
> You get 250 episodes with what? season or year based? It can be a memory limit of php ? It can be max execution time of php?
> 
> Maybe my method is not good enough to work with this kind of, in my opinion, crazy amount of episodes. For your information the tboothman version doesn't even get those episodes, it breaks the method. So i'm already glad it even works

When i use season based for one season can get maximum 250 episodes.

**Comment by Thomasdouscha** [comment]
this limit 250 episodes, for season based of course.
I think , for one season maximum 250 episodes limit is coming from imdb. Before graphql method there was not so kind of limit Even one thousand episodes we could get. Anyway it was not important it was just feedback for you.

**Comment by GeorgeFive** [comment]
I'm not going to be much help here, I don't think.  I haven't checked out this latest revision yet, but I've had absolutely no problems with the code handling season data.  I did have to update my own code a bit to compensate for the changes from boothman's version, but after doing that, this version is working wonderfully.  The data is all there, and with a few tweaks on my own code, I can display it however I like.

**Comment by Thomasdouscha** [comment]
This revision is well enough and i am gonna use it in my website. Just  i am curious that max limit 250 episodes per season of seasonbased where is coming from? For example why not have yearbased of that kind of limit? It is a little bid interesting.

**Comment by duck7000** [comment]
well how do i get to know if this limit is coming from imdb? they don't share information about it.

I guess that limit is only if you want all episodes from a tv series by one season, by year it will not reach that limit

> this limit 250 episodes, for season based of course. I think , for one season maximum 250 episodes limit is coming from imdb. Before graphql method there was not so kind of limit Even one thousand episodes we could get. Anyway it was not important it was just feedback for you.

This is not true, tboothmans version didn't return anything as the bold and the beautiful did not return season number so it breaks the method

**Comment by duck7000** [comment]
So it will stay like it is now, agree?

**Comment by Thomasdouscha** [comment]
Yes i agree but still i want to know this limit where is it come from?

**Comment by duck7000** [comment]
> Yes i agree but still i want to know this limit where is it come from?

What do you want me to say? I told you i don't know if there is such limit.
And if there is such a limit there is no information about it so nobody knows.
In a "normal" situation this limit isn't a problem, only if there are more episodes in 1 season

**Comment by Thomasdouscha** [comment]
I did not say you have to do it . Relax.

The difference in these limits and the way they used to be doesn't make sense to me. When I say "used to be," I mean much older versions. I would like to know the cause behind this difference. Something I don't understand always bothers me. That's just how I am.

Simply i say what i am feeling.

**Comment by duck7000** [comment]
Well i did like to know too but it isn't documented anywhere. It remains a guessing game.
And I'm relaxed, don't worry

The way it used to be is gone, graphql is the only way to get all the data we want. There is no alternative left.
And how realistic is it to have more than 250 episodes in 1 season? That means they have to make almost an episode a day, unrealistic to me.

Tip: make it more clear that your comments are just thoughts, not a request for a change or discussion? It was unclear to me.

**Comment by duck7000** [comment]
@all You have to understand a few things just to make things clear how i set up this library

1e This library is not a fork of tboothmans version (although some of it is the same you can't compare those 2 back to back)
2e There are changes like method names or different outputs of the methods.
3e The data source comes from IMDb graphQL endpoint, not HTML displayed on IMDb pages so the data comes in the purest form. That can mean data is different as we used to get from scraping HTML, or in a different form. That also means that we can get what IMDb graphql allows us to get as free user (for some data they require a pro membership) So they might set some limits (likely with episodes i guess) on the amount of data we get

So this makes my library very different.

I'm working on a list of all methods with description of what it does, what parameter it might have and what the return values look like. it is almost done and will be placed in wiki of this repo or in the readme. If that is done it is clear to everyone what every method is named and what it does.

**Comment by Thomasdouscha** [comment]
maximum 250 episodes for one season. If there are episodes much more this limit, getting episodes stop. 3-4 tv series i tried and i got same result. 
Maybe graphql data has some limits for example maximum filesize can be 1024kb. why do i think like this? Because there was not so limit by classic scraping. 250 episodes with included bio it will be big data. Maybe becuse of this.

**Comment by Thomasdouscha** [comment]
I have very powerfull server. I don't have any problem with my database. Some tables has records more then 12millions. Running very well. 
Later I can give you some examples for this limit in which tv series has it. If you get graphql data's filesize we can validate the couse of limit. But if it is so there is nothing to do. just we ll learn what the problem is.

**Comment by duck7000** [comment]
I did checked the bold and the beautiful and sure enough i get 250 episodes so this is definitely a limit from imdb graphql api.

No point to argue about this any longer, this is how it is.

The good news is that year based does get all episodes so if you want you can get them all, exactly like you wanted (you asked for parameter yearbased)

**Comment by duck7000** [comment]
#26 

With cast there also seems to be a limit of 250 results, i hope i fixed that.
So i believe with episodes this is the same problem.

re-open this one and i will try to fix this as well but it seems a lot more complicated then cast() so no promises

**Comment by duck7000** [comment]
I did investigate this a little bit and it is only a problem in a very edge case like the bold and the beautiful, and only when you want 28 years of episodes in one season.

Besides that it is almost impossible as tv maker to make 250 episodes in one season/year.

So i'm wondering if this is worth the trouble to try to fix this as well?

**Comment by duck7000** [comment]
It does not affect me either.
So if @Thomasdouscha has no problem with it i won't fix this.
