### ISSUE TITLE
Quote method is not implemented

### ISSUE THREAD

**Issue by jcvignoli** [duck7000/imdbphp6#24]
Hi @duck7000 
I just noticed that method quotes() in Person class doesn't implement the graphql way to retrieve IMDb info.
So it doesn't retrieve anything!
Could you take a look at it?

Thanks!

**Comment by duck7000** [comment]
well that is impossible as it works in my tests here?

It uses the same private method dataParse() as trivia and trademarks, both are working fine

I think you still use the old scraper method?
Try updating to my latest version, it should work.

**Comment by jcvignoli** [comment]
Hi @duck7000,
Thanks for you quick reply. Now I see, you replaced the method parparse() with a new parser... Ok, let me give it a try, will implement the new method, good move forward in terms of maintenance :)
Will report back should I find an issue.
Cheers

**Comment by jcvignoli** [comment]
I actually already implemented your new methods and it was actually working. I just messed up with my local dev settings.
Sorry for bothering you, closing the issue.

**Comment by duck7000** [comment]
No worries mate

I'm glad it is working for you
