### ISSUE TITLE
PHP < 7

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/imdbphp6#3]
I use an earlier version of PHP, so technically, this is not compatible with my setup.  While I've only done a quick runthrough of the code, SO FAR, I can get around this pretty simply....

title.php, add:

```
if (! function_exists("array_key_last")) {
    function array_key_last($array) {
        if (!is_array($array) || empty($array)) {
            return NULL;
        }
       
        return array_keys($array)[count($array)-1];
    }
}
```

Will dig in more as time allows....

**Comment by duck7000** [comment]
Ah i didn't think of that, i use php 8.2

So i have to change every function call array_key-Last with your proposal above?
If so is will change it asap

**Comment by GeorgeFive** [comment]
You don't have to change any of your code, just tack that quick little function down at the bottom of title.php. If a user is using PHP>=7, it will work as normal. If they're using a lesser version, it will use that function (which does the same thing as the official implementation).

Personally, I use an older version because of some legacy code that cannot be easily updated, but is integral to the site functionality.

Anyway, I don't expect you to completely rewrite your code, but most compatibility issues can be fixed with stuff like this.... and at a glance, that's the only issue preventing it from being compatible with older versions.

**Comment by duck7000** [comment]
Well every version below php 8 is eol so i don't feel comfortable to add legacy code for unsupported PHP versions.

you can however implant this yourself but i strongly suggest to upgrade and upgrade your legacy code accordingly
I have dealt with this problem myself (my program was written in php version 4) so i rewrote the code.

replacing array_key_last with this is a option:
$lastKey = key(array_slice($array, -1, 1, true)); but it is slower

**Comment by GeorgeFive** [comment]
Fair enough, I totally get where you're coming from.  Was throwing this out there for my own personal use, and it may come up later from other users as well....?

**Comment by GeorgeFive** [comment]
I haven't touched person.php yet, but so far, that's the only compatibility issue I've come across.  I'm trying to test as much as I can, as quick as I can.... but with 14+ hour work days this week, I'm strapped for time and only able to do small chunks.

**Comment by duck7000** [comment]
I.m re open this, maybe other users have the same problem
I consider to change it to a older method so php 5.6 or higher is working

**Comment by GeorgeFive** [comment]
Got another issue with the code changes from #8 :

PHP Parse error:  syntax error, unexpected '=>' (T_DOUBLE_ARROW)
in this line:
usort($this->goofs, fn($a, $b) => $a['type'] <=> $b['type'])

I don't use this function, so I can safely strip it out of my release.... just throwing this out there.

**Comment by duck7000** [comment]
mm i think this comes from the fact that you use a older php version

I can remove it, the output array is not sorted but the data is still in place

**Comment by duck7000** [comment]
I replace all array_key_last to the other solution we talked about.
The performance impact is small so after all no big deal.

The only reason it slightly bothers me is that there is finally a good solution, array_key_last(), but for compatibility reasons not usable here

If this is working right report it back here so we can close this issue successfully :)

**Comment by GeorgeFive** [comment]
I am currently using your code "straight out of the box" with no compatibility changes, so looks good!
