### ISSUE TITLE
Config options/ remove stuff

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbphp6#33]
@jcvignoli
@Tomashdoesha
@GeorgeFive
@All

Do you use any of the config options like ini override, language (i'm not sure this even work with GraphQL) or tweaking options?

I'm thinking of removing those, even to remove config itself as i never set anything there

Eventually i will remove all stuff that is related to the old scraping method, it isn't needed for GraphQL
I doubt it will ever be used again, GraphQL isn't going away anytime soon i guess.

If you have any objections or still use anything related to above let me know

**Comment by duck7000** [comment]
@GeorgeFive 
@All

I pushed a new version with all config and ini overrides removed.
Please test it out, it works fine for me

**Comment by GeorgeFive** [comment]
Everything seems fine so far, no immediate issues pop out at me.
