### ISSUE TITLE
Idea - Episode release dates

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/imdbphp6#34]
This is something that has bugged me for a while, but I'm not sure if there's much that can be done about it... throwing it out here to see if you have any ideas.  For some reason, IMDb defaults to showing the US release date for episodes, even when there are multiple dates available.

Example - https://www.imdb.com/title/tt0246734/

It says episode 1.1 was released March 7, 2000, but if you look at the releaseinfo page for that episode, you'll see the real release date... "Japan February 25, 1998"

I understand that this isn't a fault of the class, as you're grabbing info from the episodes page and they show the US date there.  I guess I could grab all of the release dates for an episode and sort them asc to get the first available date and hope that it's right, but that seems a little wonky.

Any other ideas, anything I might be missing?

**Comment by duck7000** [comment]
Remember that the data comes from GraphQL endpoint, not from the webpages, there might be differences

Currently i only get releaseDate, and that is probably always US but i noticed that there is also releaseDates and that are all release dates from a episode, maybe that is what you are looking for?
Country is also available so you can sort them by country

If that is what you want i will try to add it, releaseDate will still remain as i use that

**Comment by GeorgeFive** [comment]
Gotcha.  Yeah, I was hoping that maybe there would be an original release date field in GraphQL or something like that to make this easier.  To me, it just looks wildly inaccurate, and they only seem to do it on episodes, not titles.  As an example, if the original Godzilla (1954) was a TV episode, it would put a release date of 2004 on it because that's the US release available... this is downright dumb, haha.

https://www.imdb.com/title/tt0047034/releaseinfo/

I did see the releaseDates option and may have to do something with that to get better accuracy, was just hoping that maybe there was an easier option or maybe you had some ideas.

**Comment by duck7000** [comment]
Original release date is not available as far as i can see

Do you want all release dates to be included? This list all countries and their release dates but still don't list the first release date, only per country

**Comment by GeorgeFive** [comment]
Hmmm... I may need to play with the releasedates function a bit in this case, as this may end up making things needlessly complicated or inaccurate in other ways. Off the top of my head, if the correct date is 1998-02-25, but they have a date listed for another country as 1998-00-00, that would technically be the first date if we sort asc.... And this would be yet another issue...

**Comment by duck7000** [comment]
I see what you mean, but i have to ask: why bother with this?
I don't really care what it states as release date as long as there is a release date to display

**Comment by duck7000** [comment]
Well i'm happy to add releaseDates but it won't solve your problem so for now i think we agree to keep it like it is.

If you ever change your mind or find something useful to add to this feel free to reopen this.
