### ISSUE TITLE
Need for type in titleSearch class?

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbphp6#35]
@GeorgeFive
@All
Is there any need for this?

Personally i use all types (like it is now in titleSearch) but it can be extended to search by specific type like movie, game, podcast etc

I'm guessing not, nobody asked for it sofar

**Comment by duck7000** [comment]
Nobody seems to need this, including me the author, so closing this one

**Comment by duck7000** [comment]
re open this one as i consider to add it anyway

**Comment by GeorgeFive** [comment]
Looks good!  It didn't really help with the search amount though.  I think the problem is that imdb searches based on popular, not how close the titles actually match the search query.  This is what I'm getting back for "The Circle".... the last one is the one I actually wanted:

The Circle (2017) - Connect
Kingsman: The Golden Circle (2017) - Connect
The Circle (2020) - Connect
The Secret Circle (2011-2012) - Connect
The Bletchley Circle (2012-2014) - Connect
The Broken Circle Breakdown (2012) - Connect
The Red Circle (1970) - Connect
The Circle (2015) - Connect
Squaring the Circle: The Story of Hipgnosis (2022) - Connect
The Circle (2000) - Connect
The Circle (2018-2021) - Connect
Arctic Circle (2018) - Connect
The Bletchley Circle: San Francisco (2018-2018) - Connect
Lovers of the Arctic Circle (1998) - Connect
Full Circle (2023-2023) - Connect
The Circle (1957) - Connect
Hercules: The Legendary Journeys - The Circle of Fire (1994) - Connect
The Circle (2014) - Connect
Circle (2015) - Connect
The Circle (1925) - Connect
The Inner Circle (1991) - Connect
Mrs. Parker and the Vicious Circle (1994) - Connect
The Inner Circle (2019-2019) - Connect
The Circle (2005) - Connect

**Comment by GeorgeFive** [comment]
You have the list of title types in the wiki... are there other types not listed?  I ask, because after changing my code to search for "MOVIE,TV", I've noticed that adult titles no longer appear.

**Comment by duck7000** [comment]
for your search results i see 2 options left:

include the year in your searchTerm?
Or i can add isExactmatch as query option parameter (this will get only titles that exactly matches the searchTerm?

**Comment by duck7000** [comment]
> You have the list of title types in the wiki... are there other types not listed? I ask, because after changing my code to search for "MOVIE,TV", I've noticed that adult titles no longer appear.

No this are the types that are listed to be working, why adult don't work i don't know

Does it work with a single type like MOVIE?
Does it work if you don't provide a type?

**Comment by GeorgeFive** [comment]
Searching for "MOVIE,TV" or just "MOVIE" with query "Pirates"... https://www.imdb.com/title/tt0477457/

Pirates of the Caribbean: The Curse of the Black Pearl (2003) - Connect
Pirates of the Caribbean: Dead Men Tell No Tales (2017) - Connect
Pirates of the Caribbean: On Stranger Tides (2011) - Connect
Pirates of the Caribbean: Dead Man's Chest (2006) - Connect
Pirates of the Caribbean: At World's End (2007) - Connect
Pirates (1986) - Connect
The Pirates (2014) - Connect
The Pirates! Band of Misfits (2012) - Connect
Pirates (2021) - Connect

Using no parameters... (last one is the expected result)

Pirates of the Caribbean: The Curse of the Black Pearl (2003) - Connect
Pirates of the Caribbean: Dead Men Tell No Tales (2017) - Connect
Pirates of the Caribbean: On Stranger Tides (2011) - Connect
Pirates of the Caribbean: Dead Man's Chest (2006) - Connect
Pirates of the Caribbean: At World's End (2007) - Connect
Pirates (1986) - Connect
Pirates (2005) - Connect

**Comment by GeorgeFive** [comment]
> include the year in your searchTerm?
> Or i can add isExactmatch as query option parameter (this will get only titles that exactly matches the searchTerm?

Including year kinda works... it does indeed give the expected result as the first item, but the year has to be exactly right as it will only return items from the given year.  So if you search for "Godzilla 1997", you're not going to get Godzilla from 1998 or any other year.  In that case, I would like to see "Godzilla" from 1997 given more weight and ranked higher as I specified a year, but 1998 and other year versions should be returned as well.

isExactmatch could be an idea, but this goes back to the previous statement.... just like the name says, it would have to be exact.  Maybe use isExactmatch to sort the array a little better, but not exclude items that don't exactly match?  So this would change my above Circle example to...

The Circle (2017) - Connect
The Circle (2020) - Connect
The Circle (2015) - Connect
The Circle (2000) - Connect
The Circle (2018-2021) - Connect
The Circle (1957) - Connect
The Circle (2014) - Connect
The Circle (1925) - Connect
The Circle (2005) - Connect
The Circle (2017) - Connect
Kingsman: The Golden Circle (2017) - Connect
The Secret Circle (2011-2012) - Connect
The Bletchley Circle (2012-2014) - Connect
The Broken Circle Breakdown (2012) - Connect
The Red Circle (1970) - Connect
Squaring the Circle: The Story of Hipgnosis (2022) - Connect
Arctic Circle (2018) - Connect
The Bletchley Circle: San Francisco (2018-2018) - Connect
Lovers of the Arctic Circle (1998) - Connect
Full Circle (2023-2023) - Connect
Hercules: The Legendary Journeys - The Circle of Fire (1994) - Connect
Circle (2015) - Connect
The Inner Circle (1991) - Connect
Mrs. Parker and the Vicious Circle (1994) - Connect
The Inner Circle (2019-2019) - Connect

https://stackoverflow.com/questions/41240595/how-to-sort-array-by-matching-the-closest-to-input-string
This could be a pretty slick way of doing it, but this could get complicated for the class.... I could implement it in my own code, if you don't want to place it in the overall class?

**Comment by duck7000** [comment]
Mmm my thoughts

"pirates" as searchTerm is too common i guess? In this case you need to be more specific, for example with a year. But yes that would be a exact year likewise isExactMatch would do

I'll try to find the bug with no adult results (i think it is bug)

**Comment by duck7000** [comment]
And the stackoverflow link is certainly interested but i think it is going far beyond the scope of this library so if you want to use that implant it in your app

**Comment by GeorgeFive** [comment]
Now that I dig deeper, yeah, I think it's the "VIDEO" type that is screwing things up, and I just happened to notice it on a couple of adult titles.

**Comment by duck7000** [comment]
So it all works fine i presume?

**Comment by GeorgeFive** [comment]
I do believe so.  They definitely need an option for VIDEO, but I realize that's out of our control here.

**Comment by duck7000** [comment]
The problem is that within mainSearch there are less and different titleTypes then there are available in Title itself
So you can only filter those few types, the point of using this filter is limit i guess

I will close it for now, if there is any change in the future we can discus it again.
Thanks for testing though!

**Comment by duck7000** [comment]
Imdb added a new option to the mainSearch method
Search by year or year span is now supported so i'm thinking to implant that too

That would solve your issues above as you can provide a year span

I'm working on it
@GeorgeFive

**Comment by GeorgeFive** [comment]
Looking good!

**Comment by duck7000** [comment]
Thanks!
