### ISSUE TITLE
Bringing back caching

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbphp6#39]
@GeorgeFive
@All

After long thinking about this and repeatedly asked for #33, #17 i am bringing back the caching system.
I already have it working in a test environment but need to test person class as well

As far as tested it works but it is disabled by default (as i don't use it)
All config options are in cache.php  but that is no longer a valid option (as there are 5 options for caching alone) so i'm also bringing back config.php, but that is not re-implanted jet.
Config is also needed for the recently added language options, those config options are now in GraphQL but should be in config as well.

When it is done i need you all to fully test it as you are the ones that will use it.

This project started as i very stripped down version of imdbphp but it is growing fast into a full blown version that i'm no longer threat it as such. 

So if there are more requests (like advanced search, search by type etc.) let me know.

**Comment by GeorgeFive** [comment]
I will definitely be testing this out, as this will help me out a lot!

If you're wanting ideas for other stuff, I can definitely make some new threads for you... had a few recently.

**Comment by GeorgeFive** [comment]
I just tested this out with all major use-cases (person, title, title-series), and saw no issues to speak of.  If I see anything pop up, I'll let you know.  I'll go ahead and post a few ideas in new threads since you asked, and we'll see what happens.  Thanks!

**Comment by duck7000** [comment]
Nice!, that is great news!

An advantage of the config file is that if i release a new version you can use the old config file. If there are changes in that config file i will explain in the release notes.

**Comment by GeorgeFive** [comment]
Any chance we could move the title count from TitleSearch over to the config?  Default is set to 10, I prefer to get more, and I have to update it every time there's a new release.

**Comment by duck7000** [comment]
Sure i can, what would you prefer as default?

10 is for my use case enough but 15 is also fine i guess

And next time please open a new issue, otherwise issues will clutter with stuff that has nothing to do with the issue:)

**Comment by GeorgeFive** [comment]
Default can stay 10 or so... I just prefer 30 because it seems to get weird with more common title names.  An example I was just working on (that reminded me to update the setting), The Circle (2005)... it shows up as result #25, with a bunch of other movies above it that don't have that exact title.  With the default of 10, I couldn't find this title.

And yeah, I usually try to open new tickets, I just threw it here because we were talking about the config, hah.  Thanks!

**Comment by duck7000** [comment]
No problem, changes already merged so check it out.
