### ISSUE TITLE
Title > Producers

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/imdbphp6#4]
Producers function does not seem to be converted yet.... errors out with:

Call to undefined method Imdb\Title::get_table_rows()

I did not try principal_credits, but otherwise, the other credits functions seemed to work properly.

**Comment by duck7000** [comment]
Mm i totally forgot to upload it..
I made it locally on my computer but never uploaded

But it is uploaded now!

Thanks for testing

**Comment by GeorgeFive** [comment]
Awesome, working great!
