### ISSUE TITLE
Streaming info

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/imdbphp6#40]
IMDb recently added an option to show links to where a movie is available to stream.... this is available on pretty much every movie, but here's an example:

https://www.imdb.com/title/tt2236182/

Any chance we could grab this information?

**Comment by duck7000** [comment]
I can't seem to find any links to streaming services on the above link?

screenshot maybe helps?

**Comment by GeorgeFive** [comment]
Hmmm... maybe this is region specific?
![1](https://github.com/duck7000/imdbphp6/assets/9860649/f78ee67c-e485-4cdc-9d8e-e74f82419853)
![2](https://github.com/duck7000/imdbphp6/assets/9860649/abeac514-5dcc-4231-a051-3b10049abbd3)

**Comment by duck7000** [comment]
That streaming info is only available for this services:

Watch option constraints are limited to region of the request.
Region is determined by the x-imdb-detected-country header (gateway determines from request).

WatchOptionsSearchConstraint currently supports a limited set of providers:

'amzn1.imdb.w2w.provider.amazon' (Amazon physical purchase)
'amzn1.imdb.w2w.provider.prime_video': (Prime Video purchase/rental)
'amzn1.imdb.w2w.provider.prime_video.PRIME' (Prime Video subscription)
'amzn1.imdb.w2w.provider.prime_video.freevee' (Freevee free/ads)

The region can be overridden if necessary.
But Netflix can not be used

I think that this is complicated, region bounded etc

The only thing i get working is if i use any of the watch options above the results are within that watch option but the watch option is not shown in the results

**Comment by GeorgeFive** [comment]
Dammit... it was worth a try.  They might be getting their data from JustWatch, but I'm not a big fan of their way of doing things.... but I guess that's a whole other can of worms, hah.

**Comment by duck7000** [comment]
Closing this one, as it not very likely that imdb will support other streaming services
