### ISSUE TITLE
Renaming class names

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbphp6#44]
@All
I'm thinking of renaming the following class names and file names:

Classname Person to Name
Person.php to Name.php
Classname PersonSearch to NameSearch
PersonSearch.php to NameSearch.php

The reason is simply because imdb uses those names in their GraphQL API, so it is easier to follow their naming scheme.
The second reason is to be more distinguish from imdbphp.

What is your view on this?
 @GeorgeFive

**Comment by GeorgeFive** [comment]
I'm completely neutral on this one.  Won't affect me if you change it (simple fix on my end), wouldn't be upset if you left it.  Your call!

**Comment by duck7000** [comment]
Thanks, i already changed it hah

This change is not in the latest release jet, i will make another release soon
