### ISSUE TITLE
New methods Name class

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbphp6#46]
I added a few missing methods to the Name Class

children()
parents()
relatives()

All info is in the wiki

**Comment by duck7000** [comment]
another new method

Added akaName method to Name Class, Gets all alternative names for a person (all info is in the wiki)

**Comment by duck7000** [comment]
Another new method:

Added credit method to Name Class, Gets all credits for a person (all info is in the wiki)

therefor i needed to add graphqlGetAll method to get all results

**Comment by duck7000** [comment]
@GeorgeFive

I hope that your medical issue is getting better?

In case you are bored (i would, i hate been sick) i added new methods to Name and Title class
I added them for completeness (as this is going to be a full blown version anyway) rather then somebody asked for it.

It is better to add them now i know how it works.

There are still methods used at imdb that does not have a method here so if you want them added as well let me know

But most important get well soon.

**Comment by GeorgeFive** [comment]
Yeah, I'm doing ok.... I screwed up my back (slipped discs), so sitting at my desk for any period of time starts to hurt, so it's been fun!  Physical therapy is helping, I guess.  Fun stuff.

Anyway... what is the difference between the new akanames and the previous nicknames?  I see nicknames is still there, but I can't seem to find anyone on imdb who has akanames attached.  Can you show me an example?

Going to use children() parents() relatives() in my own script, I'll let you know how that goes!

**Comment by GeorgeFive** [comment]
I just added in children() parents() relatives() and spouses, all looks good.

**Comment by duck7000** [comment]
I'm glad you are getting better!

akaNames is with this person https://www.imdb.com/name/nm0000314/ (scroll to personal details)
This is a alternative name the person is know of, that is different from nickName. Mostly the writing of the name is different (like i or y at the end in this case)

**Comment by GeorgeFive** [comment]
Gotcha... yeah, I already used nickname in my setup, which is what sort of confused me, hah.  I thought it was going to be the same thing.  I see the difference now, I was looking for akanames on bio and coming up empty.

**Comment by duck7000** [comment]
I also added rank method to the name class

It will get the popularity rank of a person, the same as the title method rank.
It can be used to display a top 500 position, or top250 etc

**Comment by duck7000** [comment]
And i added pubother method

It will get all other works of a person not listed in publicity lists
All info is in the wiki

**Comment by GeorgeFive** [comment]
Question about spouses (I added this in along with the other family stuff you just added).  It seems that on imdb, there can be a difference no "spouse to" date set, which implies that they are still together... this seems to be the norm.  However, there can also be no date set, which means that they don't know the date.

On the site, they somehow know the difference... ie,

https://www.imdb.com/name/nm0957772/bio/
Sheri Moon Zombie (October 31, 2002 - present)

https://www.imdb.com/name/nm1337935/bio/
Jeanne Clarke

On our end, we can't tell the difference, we just get nothing for the "to date".  Would it be possible to get the "present" comment?

**Comment by duck7000** [comment]
I added current to spouse() so you can use that to check if true (present) or false

I can however also add the whole date string as full text (in this case it will include present) if you want?
It is not hard to do so probably i will add it anyway

**Comment by GeorgeFive** [comment]
current sounds like exactly what I need.... I'll test later tonight when I get home.  In that case, I probably won't need the full text, but if it's there, might be nice (would save me from doing all sort of if/else on to/from, haha).

**Comment by duck7000** [comment]
I added dateText to spouse, This is the fromDate and toDate in plaintext as displayed at imdb

**Comment by GeorgeFive** [comment]
Looks good, those both help and things look right now!

**Comment by duck7000** [comment]
Nice and thanks, we can close this one as all works
