### ISSUE TITLE
Multiple fixes and additions

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbphp6#49]
* Title class changed output of Director, composer, producer, writer, thanks, stunts, visual effects, cinematographer and special effects to output array instead of string for jobs and episode credits
* Title class episode, photo parameter thumb is true or false, true == thumbnail, false == large image max 1000 pixels
* Name class photo parameter thumb is true or false, true == thumbnail, false == large image max 1000 pixels
* Title class added thanks,stunts,visual effects and special effects methods
* Title and Name class added checkRedirect to check if an imdbid is redirected or not
* Title and Name class added externalSites method
* fixed multiple doc blocs

@GeorgeFive
The first change in this list will need your attention as the output array of those methods is changed.
It used to output string for episode and jobs but now it outputs array with all those items separated.
I tried to explain it all in the wiki but i might missed something

**Comment by GeorgeFive** [comment]
Haven't had a chance to look at the code yet (work), but has anything changed with special / visual effects?  I took the code out on my end, so curious if anything changed and if I should try it again?

**Comment by duck7000** [comment]
No the method that collects the data hasn't changed (there lies your problem) so try again will not help.

I'm working on bringing back the logger so you can check if the return from GraphQl is correct or not

**Comment by GeorgeFive** [comment]
Sounds good, let me know when you've got the logger running.  Updated the job arrays on my end, no issues there.

**Comment by duck7000** [comment]
@GeorgeFive 
Logger is back added, use config option $debug to true to enable
For the moment it only works on the imdb api call

**Comment by duck7000** [comment]
closing this one as the changes seem to work, for logger questions please use the other issue
