### ISSUE TITLE
Request: Companies data / rating count

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/imdbphp6#5]
I believe these are the only things missing from title.php that I personally use.  Would it be possible to port over company data (namely, production company and distributor) as well as user rating counts?

This has already been converted to graphql in boothman's version....

**Comment by duck7000** [comment]
I'll think about it

And by user rating you mean?
![Screenshot_2023-08-03_17-11-39](https://github.com/duck7000/imdbphp6/assets/15360048/3f480039-6d62-4354-8e5e-94f08091e5e1)

**Comment by duck7000** [comment]
company credits is added back and converted to GraphQL

I don't want to add too much stuff that i don't use so i will add votes and that would be the last unless you have serious need for something else

**Comment by duck7000** [comment]
Votes is added too

**Comment by GeorgeFive** [comment]
Works great, thanks for the speedy updates!
