### ISSUE TITLE
250 limit strikes again

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/imdbphp6#50]
If a movie has more than 250 visual effects credits (and I would assume special effects / thanks / stunts), we only get the first 250.  Example....

https://www.imdb.com/title/tt14539740/fullcredits

**Comment by duck7000** [comment]
Mm i would have thought that this kind of bugs didn't occur anymore by now but here we go again haha

I'll check if there is no limit at imdb (some api methods have warning text that it is limited to 100 items)
If that is not the case i will have to convert that to the paginated Graphql method, if so all methods that use this helper method are going to use that (writer,director,composer,producer,thanks,stunts,specialeffects and visualeffects)

**Comment by duck7000** [comment]
I think i fixed it.
writer, director, composer, producer, thanks, stunts, specialeffects, cinematographer and visualeffectsmethods now returns (if available) more than 250 items

May be there are others that also need conversion to GraphQLAll?

**Comment by GeorgeFive** [comment]
I haven't seen any others that come close to hitting 250... I guess, theoretically, filming locations could need it, but the most I've seen for a given title so far is 114.  I don't use movie release dates or movie also known as, but maybe they could hit it (though I have no examples).

Anyway, fix worked great, thanks as always!

**Comment by duck7000** [comment]
I made a helper method to strip the spaces, it might occur again so this is easier.

Thanks!
This way our version will become better and better

**Comment by duck7000** [comment]
I'm thinking of those methods:

keywords
companyCredits
crazyCredits
trivia
goof
quote
award (this is a big one and could also need stripSpaces as the query is large)

location is also a possible candidate, thanks

also known as and releasedates i think that those not become above 250 (aka is always a fixed number of countries, always lower than 250 as far as i have seen)

It is not hard to convert (although the query is a bit different) so i will look in to this

**Comment by GeorgeFive** [comment]
For AKA.... there can be akas with no country set, or multiple per country.... ie, 

https://www.imdb.com/title/tt0069745/releaseinfo/

Again, I've never seen one above 250, but I guess it's possible.  Same with release dates, there can be numerous dates per country, but even though I've never seen one go above 250, I guess it's possible.

I could definitely see those other methods going above 250 with certain examples.

**Comment by duck7000** [comment]
Mm okay i'll put aka and releaseinfo to the list, thanks for the example

**Comment by duck7000** [comment]
I'll re open the other issue about 250 items limit
