### ISSUE TITLE
Trivia categories

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbphp6#51]
@GeorgeFive
I recently found out that trivia actually contains categories just like connections.

The current triva method fetches all categories in one array with or without spoilers.

Is it an idea to make triva (and possibly other methods, not sure jet) categorized just like connections?
Or is it fine like it is?

These are the possible categories:
actor-trademark
cameo
director-cameo
director-trademark
smithee
uncategorized

**Comment by GeorgeFive** [comment]
I personally do not use trivia, but if I did... yeah, I'd say categorized would be the way to go.  At least have the data there and give the option to use it if they want.

**Comment by duck7000** [comment]
Goof uses categories as well so i will make those two methods categorized just like connections
Separate data is a better option i agree

Thanks for your reaction.

**Comment by duck7000** [comment]
goof and trivia are now categorized and as far as tested it works great (although i don't use it all myself)

So closing this one as complete
