### ISSUE TITLE
Director = jobs

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/imdbphp6#52]
Most credits have jobs attached to them (ie, producer, stunts, effects, etc).... but director does not have this info available.  It's not very common, but it does exist in some places, ie

https://www.imdb.com/title/tt0162503/fullcredits

Any chance you could throw that in?  Thanks!

**Comment by duck7000** [comment]
It is very rare indeed, your example is the first i've seen so i left it out on purpose.

i will try to add it back soon, at the moment i'm still busy with all the conversion to graphQlGetAll and with the conversion of trivia and goof to categorized output array (trivia was harder than expected)

**Comment by duck7000** [comment]
This is not a job but an attribute. Director writer and composer does not have jobs (although not impossible i guess)

I'll look in to it

**Comment by GeorgeFive** [comment]
Sounds good!  No huge rush, just whenever you get the time.

**Comment by GeorgeFive** [comment]
Everything looks good!  Director and composer attributes are incredibly rare, but I figured it was worth having if they offer it.

Thanks!

**Comment by duck7000** [comment]
Do note that the episode info for director is not accurate as the query is missing some info i can't seem to find so best to not use that. (i doubt somebody is using this at all)
All others are correct (if available)
