### ISSUE TITLE
protected function stripSpaces

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/imdbphp6#53]
Quick note... you forgot to include protected function stripSpaces in Name.php

**Comment by duck7000** [comment]
Right.. oops i totally forgot that it is not included at all, i'will correct that soon

**Comment by duck7000** [comment]
latest git correct this problem, thanks!

**Comment by GeorgeFive** [comment]
All good!

**Comment by duck7000** [comment]
Thanks for watching haha
