### ISSUE TITLE
Re wrote the stripSpaces part

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbphp6#55]
@GeorgeFive
We needed to add a function to strip spaces from querys to lower the character count due to hosters requests limits.
I added a function for that and used it in almost all method but later i came up with a much more clever idea to integrate this inside the graphQl functions, so i did.
All methods are now using the strip spaces part inside query() and graphQlGetAll() instead of doing this in every method, this is way more efficient

Would you mind  a quick test if all methods are still functioning at your server?

**Comment by GeorgeFive** [comment]
Did a few quick tests and everything looks good!  Got all title credits as expected, filming locations, individual name info / pictures, etc etc etc.

**Comment by duck7000** [comment]
Nice, thanks for testing!
