### ISSUE TITLE
Found some odd new methods for Tittle class

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbphp6#56]
@GeorgeFive
@All
I found in graphQl some methods that are not in imdbphp6 jet but might be odd

FilmingDates (dates of filming this title) (not sure why anyone would want this?)
ProductionDates (dates of producing the title) (not sure why anyone would want this?)
isAdult (boolean indicating this title been adult or not)
news (those are the news articles found in a title)
parentsGuide (this will get provanity,sex,drugs etc of a title)
productionStatus (this will get the status of a title like released or not etc)
relatedLists (not sure but it looks like top picks max 10 available)

Is this worth it to add in our version? For completeness i would say yes but i will never use it

**Comment by GeorgeFive** [comment]
Can't say I would use any of that stuff... isAdult might be helpful for some, but I already do my own stuff to filter that.

**Comment by duck7000** [comment]
thanks for your comment

I added isAdult method to the title class, very easy method ouputs boolean

The rest will not be included as none of us would use it
