### ISSUE TITLE
Found some odd new methods for Name class

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbphp6#57]
@GeorgeFive
@All

In the Name class there are some more methods not included in imdbphp6 but maybe odd

news (news articles found on the person name page)
relatedLists (not sure but this might be top picks)
sharedNames (if for example father and son both played together in a title it will be listed in here)
sharedTitles (if for example father and son both played together in a title it will be listed in here)
disambigator (if there are more persons with the same name imdb gives them a I or II after the name)
demographicData (this will get gender for a specific person)

photo and videos of a person are also missing but GeorgeFive already said that this is of no interest

Would this be worth to include? for completeness i would say yes but i will never use it

**Comment by GeorgeFive** [comment]
Can't say I would use any of that stuff...

**Comment by duck7000** [comment]
thanks for your comment

I will leave it out then as none of us will ever use it.
