### ISSUE TITLE
Time for a name change?

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbphp6#59]
@GeorgeFive
@all

Maybe it is time to change the name of this repo?
I get the feeling that most people who come here think that this is a fork or clone of imdbphp, although i made that very clear that is not the case.
The name of my repo is in that sense too much  the same as imdbphp so i think about to change it

Suggestions are welcome!

I'm thinking about this:

imdbGraphQL
imdbPHPAPI
imdbAPI
imdbGraphQLApi
imdbGraphQLPhpApi
imdbGraphQLPhpAPI
imdbPhpGraphQL
imdbPHPGraphQL

**Comment by GeorgeFive** [comment]
I'm not opposed to the idea... maybe imdbPHPGraphQL to cover all bases?

**Comment by duck7000** [comment]
Thanks for your suggestion, i like that one too although it might be too long?

Maybe this is better?
imdbGraphQL

**Comment by GeorgeFive** [comment]
The only thing I was thinking of is google / github traffic.  If I was searching for a library like this, I would immediately search for "imdb php" or something like that.  I know it uses graphql, but I wouldn't search for that if I was looking for something like this...

**Comment by duck7000** [comment]
Mm good point, thanks

imdbGraphQLPHP?
That follows the name scheme of my other projects like musicBrainzPHP and discogsPHP

**Comment by GeorgeFive** [comment]
That would work!

**Comment by mosource21** [comment]
> imdbGraphQLPHP? That follows the name scheme of my other projects like musicBrainzPHP and discogsPHP

I like this for being descriptive and much better than the current name which makes it seem like it only works with PHP v6

**Comment by duck7000** [comment]
@mosource21 
Thanks, this is also a good point.

I have decided to make it imdbGraphQLPHP

Thanks everyone for thinking about this.
